# AUTOGENERATED FROM 'app/polls/get_poll.edgeql' WITH:
#     $ edgedb-py

# ruff: noqa: E501

from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetPollResult(NoPydanticValidation):
    id: uuid.UUID
    question: str
    description: str | None
    answers: list[GetPollResultAnswersItem]


@dataclasses.dataclass
class GetPollResultAnswersItem(NoPydanticValidation):
    id: uuid.UUID
    text: str
    votes: int


async def get_poll(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetPollResult | None:
    return await executor.query_single(
        """\
        select Poll {id, question, description, answers: {id, text, votes}} filter .id = <uuid>$id;\
        """,
        id=id,
    )
