# AUTOGENERATED FROM 'app/polls/vote.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class VoteResult(NoPydanticValidation):
    id: uuid.UUID


async def vote(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> VoteResult | None:
    return await executor.query_single(
        """\
        update Answer
        filter .id = <uuid>$id
        set {
            votes := .votes + 1
        };\
        """,
        id=id,
    )
